# http://www.appveyor.com/docs/appveyor-yml

# Fix line endings in Windows. (runs before repo cloning)
init:
  - git config --global core.autocrlf true

# Test against these versions of Node.js.
environment:
  matrix:
    - nodejs_version: "0.12"

cache:
  - node_modules                    # local npm modules
  - bower_components

# Install scripts. (runs after repo cloning)
install:
  - git rev-parse HEAD
  # hide python so node-gyp won't try to build native extentions
  - rename C:\Python27 Python27hidden
  # Typical npm stuff.
  - md C:\nc
  - npm config set cache C:\nc
  - npm install -g bower
  - npm install -g grunt-cli
  - npm install --no-optional --no-bin-links
  - bower install

# Post-install test scripts.
test_script:
  # Output useful info for debugging.
  - npm version
  - npm test

deploy_script:
  - ps: grunt deployWinDevBuild

# Don't actually build.
build: off
# Set build version format here instead of in the admin panel.
version: "{build}"